import math

# game settings
RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH, HALF_HEIGHT = WIDTH // 2, HEIGHT // 2
FPS = 60

PLAYER_POS = 1,1.2 # MINI_MAP
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)

# ray casting settings
FOV = math.tau / 6  # FOV = field of view
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20  # max intersections with walls

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)  # distance from player to screen
SCALE = WIDTH // NUM_RAYS  # scale of the wall

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

NUM_TILES_H = 16
NUM_TILES_W = 13
MAP_BACKGROUND = (0, 0, 0, 128)

TILE_MAP_W, TILE_MAP_H = 16, 16

MAP_SIZE_W = TILE_MAP_W * NUM_TILES_W
MAP_SIZE_H = TILE_MAP_H * NUM_TILES_H

MAP_POS_W, MAP_POS_H = WIDTH // 8, (HEIGHT - MAP_SIZE_H) // 2
